---
title: "Topic Model zu GermaParl"
author: "Andreas Blaette, Christoph Leonhardt"
date: "Stand: 18. Juli 2018"
output:
  ioslides_presentation:
    css: css/stylesheet.css
    logo: img/polmine.png
    widescreen: yes
  slidy_presentation: default
editor_options:
  chunk_output_type: console
---

## LDA Topic Model zum GermaParl-Korpus {.smaller}

- Initialisieren von Bibliotheken

```{r, eval = TRUE}
library(polmineR)
library("GermaParl")
library(topicmodels)
```

- Laden des (optimierten) Topic Model

```{r, eval = TRUE}
# GermaParl::germaparl_download_lda(k = 250L)
lda <- germaparl_load_topicmodel(k = 250)
x <- terms(lda, 50)
```


## Spalten 1-5 {.smaller}

```{r, echo = FALSE}
DT::datatable(x[,1:5])
```


## Spalten 6-9 {.smaller}

```{r, echo = FALSE}
DT::datatable(x[,6:9])
```

## Spalten 10-14 {.smaller}

```{r, echo = FALSE}
DT::datatable(x[,10:14])
```

## Spalten 15-19 {.smaller}

```{r, echo = FALSE}
DT::datatable(x[,15:19])
```


## Migrations-Topics {.smaller}

```{r, echo = FALSE}
mig_topics <- c(133, 213, 229)
DT::datatable(x[, mig_topics])
```


## Kontexte von Migrations-Topics I {.smaller}

```{r, echo = FALSE}
mig_contexts <- c(9, 65, 137, 156, 218, 249, 250)
DT::datatable(x[, mig_contexts[1:4]])
```


## Kontexte von Migrations-Topics II {.smaller}

```{r, echo = FALSE}
DT::datatable(x[, mig_contexts[5:7]])
```